name: Django Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8


      - name: Install ChromeDriver
        run: |
          LATEST_CHROMEDRIVER=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR)
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER/chromedriver_linux64.zip
          unzip /tmp/chromedriver.zip -d /tmp
          sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
      

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install -y libgconf-2-4

      - name: Set up Django
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run PyCodeStyle
        run: |
          pycodestyle blog

      - name: Run PyFlakes
        run: |
          pyflakes blog 

      - name: Run Server
        run: python manage.py runserver &

      - name: Run tests
        run: |
          export PATH=$PATH:/usr/local/bin/
          pytest -vv