name: Build and Run Django Project on Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create and migrate database
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: Set up environment variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=your_blog.settings" >> $GITHUB_ENV
      - name: Run tests
        run: pytest
